export const references=[
 {id:'allopipe',year:'2026',title:'AlloPipe: directional donor–recipient mismatches and HLA-I candidate peptides',url:'https://doi.org/10.1111/tan.70590',use:'Separate genomic mismatch from peptide presentation. This prototype imports annotated missense peptides and predictor output; it does not run AlloPipe.',de:'Genetische Unterschiede und Peptidpräsentation getrennt prüfen. Dieser Prototyp importiert annotierte Peptide und Vorhersagewerte; AlloPipe wird nicht ausgeführt.'},
 {id:'cieri',year:'2024 online / 2025 issue',title:'Cieri et al. — Systematic identification of minor histocompatibility antigens',url:'https://doi.org/10.1038/s41587-024-02348-3',use:'Research context for integrating donor–recipient genetics and miHA evidence. This implementation is not a reproduction or clinical validation of the published method.',de:'Forschungskontext zur Integration von Spender-Empfänger-Genetik und miHA-Evidenz. Keine Reproduktion oder klinische Validierung der publizierten Methode.'},
 {id:'penter',year:'2024',title:'Penter et al. — Tracking donor and recipient cells using mitochondrial mutations',url:'https://doi.org/10.1158/2643-3230.BCD-23-0138',use:'Record donor-origin evidence separately from TCR identity; a sample collected after transplantation is not automatically donor-derived.',de:'Spenderherkunft getrennt von der TCR-Identität dokumentieren; eine Probe nach Transplantation ist nicht automatisch spenderstämmig.'},
 {id:'lab',year:'Research programme',title:'Penter Lab — cancer / immune co-evolution and leukemia-specific T cells',url:'https://www.penterlab.org/projects/',use:'Motivates longitudinal blood/marrow context and the separation of immune response from malignant clonal change. Independent prototype; no institutional affiliation.',de:'Motiviert longitudinale Blut-/Knochenmarkanalyse und die Trennung von Immunantwort und malignen Klonen. Unabhängiger Prototyp ohne institutionelle Zugehörigkeit.'},
 {id:'ha1',year:'2024',title:'Krakow et al. — HA-1-targeted TCR T-cell therapy after transplantation',url:'https://doi.org/10.1182/blood.2024024105',use:'Clinical translation is a separate evidence and regulatory stage. A software shortlist is not eligibility for treatment or a clinical study.',de:'Klinische Translation ist eine separate Evidenz- und Zulassungsstufe. Eine Software-Auswahl begründet keine Therapie- oder Studieneignung.'},
 {id:'netmhc',year:'Method reference',title:'NetMHCpan 4.1 — output definitions and percentile ranks',url:'https://services.healthtech.dtu.dk/services/NetMHCpan-4.1/',use:'EL percentile rank is imported and labelled with predictor provenance. A binding prediction is not measured presentation or T-cell recognition.',de:'EL-Perzentilrang wird mit Herkunft des Prädiktors importiert. Eine Bindungsvorhersage ist keine gemessene Präsentation oder T-Zell-Erkennung.'},
 {id:'airr',year:'Community standard',title:'AIRR Community — rearrangement and repertoire standards',url:'https://docs.airr-community.org/',use:'AIRR-named fields are used in a documented single-cell import subset. Full AIRR compliance is not claimed.',de:'AIRR-Feldnamen werden in einer dokumentierten Einzelzell-Teilmenge unterstützt. Keine vollständige AIRR-Konformität.'},
 {id:'scirpy',year:'Maintained documentation',title:'Scirpy — receptor QC, chain pairing and clonotypes',url:'https://scirpy.scverse.org/en/latest/tutorials/tutorial_3k_tcr.html',use:'Preserve paired, orphan and ambiguous receptor states; clonotype identity is not antigen specificity. No embedding or sequence-similarity inference is fabricated.',de:'Gepaarte, ungepaarte und mehrdeutige Rezeptoren getrennt halten. Klonidentität ist keine Antigenspezifität; keine erfundene Einbettung oder Ähnlichkeitsanalyse.'},
 {id:'gdpr',year:'EU framework',title:'GDPR / DSGVO — Articles 5, 9, 25, 32 and 89',url:'https://eur-lex.europa.eu/eli/reg/2016/679/oj/eng',use:'Browser-local processing reduces data transfer but does not establish compliance. Real genetic/health data need an institutional legal basis, access controls and appropriate safeguards.',de:'Lokale Browserverarbeitung reduziert Datenübertragung, begründet aber keine Konformität. Reale Genetik-/Gesundheitsdaten benötigen institutionelle Rechtsgrundlage, Zugriffskontrollen und Schutzmaßnahmen.'},
 {id:'bdsg',year:'German framework',title:'BDSG §27 — scientific research data processing',url:'https://www.gesetze-im-internet.de/bdsg_2018/__27.html',use:'Research-specific conditions and safeguards require institutional assessment; pseudonymization is not anonymization. This deployment is for synthetic or approved de-identified research examples.',de:'Forschungsspezifische Bedingungen und Schutzmaßnahmen erfordern institutionelle Prüfung. Pseudonymisierung ist keine Anonymisierung; diese Bereitstellung dient synthetischen oder freigegebenen de-identifizierten Forschungsbeispielen.'},
];
